version: 0.0

os: linux

files:
  - source: \
    destination: \
hooks:
  ApplicationStop:
    - location: /stop-process.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: /start-process.sh
      timeout: 180
      runas: root