version: 0.0

os: linux

files:
  - source: vendar-0.0.1-SNAPSHOT.jar
    destination: /
    overwrite: true
  - source: stop-process.sh
    destination: /
    overwrite: true
  - source: start-process.sh
    destination: /
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: /stop-process.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: /start-process.sh
      timeout: 180
      runas: root