version: 0.0

os: linux

files:
  - source: vendar-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/
    overwrite: true
  - source: stop-process.sh
    destination: /home/ec2-user/
    overwrite: true
  - source: start-process.sh
    destination: /home/ec2-user/
    overwrite: true
  - source: aws.properties
    destination: /home/ec2-user/
    overwrite: true
file_exists_behavior: OVERWRITE
# hooks:
#   ApplicationStop:
#     - location: /vendAR/stop-process.sh
#       timeout: 180
#       runas: ec2-user
#   ApplicationStart:
#     - location: /vendAR/start-process.sh
#       timeout: 180
#       runas: ec2-user