version: 0.0

os: linux

files:
  - source: vendar-0.0.1-SNAPSHOT.jar
    destination: /vendAR
    overwrite: true
  - source: stop-process.sh
    destination: /vendAR
    overwrite: true
  - source: start-process.sh
    destination: /vendAR
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  # ApplicationStop:
  #   - location: /stop-process.sh
  #     timeout: 180
  #     runas: root
  ApplicationStart:
    - location: vendAR/start-process.sh
      timeout: 180
      runas: root