version: 0.2

phases:
  build:
    commands:
      - cd backend
      - mvn install -DskipTests
      - cd
artifacts:
  files:
    - backend/target/vendar-0.0.1-SNAPSHOT.jar
    - backend/appspec.yaml
    - scripts/stop-process.sh
    - scripts/start-process.sh
  discard-paths: yes