version: 0.2

phases:
  pre_build:
    commands:
      - aws s3 cp s3://your-bucket/path/to/file ./backend/
  build:
    commands:
      - cd backend
      - mvn clean install
artifacts:
  files:
    - target/*.jar