version: 0.2

phases:
  pre_build:
    commands:
      - wget https://vendar-bucket.s3.eu-central-1.amazonaws.com/aws.properties ./backend/
  build:
    commands:
      - cd backend
      - mvn clean install
artifacts:
  files:
    - target/*.jar