version: 0.2

phases:
  pre_build:
    commands:
      - aws s3 cp s3://vendar-bucket/aws.properties ./backend/
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./mvnw package
artifacts:
  files:
    - backend/target/*.jar

