version: 0.2

phases:
  pre_build:
    commands:
      - aws s3 cp s3://vendar-bucket/aws.properties ./backend/
  build:
    commands:
      - cd backend
      - maven clean install
artifacts:
  files:
    - target/*.jar